import type { CompanySourceConfig } from "./types";

export const trackedCompanyConfigs: CompanySourceConfig[] = [
  {
    id: "aeromexico",
    name: "Aeromexico",
    ticker: "AERO",
    displayTicker: "AERO",
    market: "US",
    industry: "航空客运、货运与忠诚度业务",
    irUrl: "https://www.aeromexico.com/",
    secCik: "0001561861",
    sourceProvider: "sec",
    parserProfile: "aeromexico-20f-2025",
    filingForms: ["20-F", "6-K"],
    filingKeywords: [
      "consolidated statements of profit or loss",
      "total revenue",
      "passenger revenue",
      "profit from operating activities",
      "income for the year",
      "financial results",
    ],
    excludeFilingKeywords: [
      "annual ordinary shareholders",
      "beneficial ownership",
      "schedule 13g",
      "form 3",
      "form 4",
      "shareholders' meeting",
    ],
    knownReports: {
      "2025FY": {
        fiscalYear: 2025,
        fiscalQuarter: "FY",
        periodLabel: "2025 FY",
        releaseDate: "2026-04-30T20:31:26.000Z",
        title: "Grupo Aeromexico 2025 Form 20-F",
        sourceUrl:
          "https://www.sec.gov/Archives/edgar/data/1561861/000119312526197494/d101275d20f.htm",
      },
    },
  },
  {
    id: "alibaba",
    name: "阿里巴巴",
    ticker: "9988.HK",
    displayTicker: "9988.HK / BABA",
    market: "HK",
    industry: "电商、云、本地生活与数字媒体",
    irUrl: "https://www.alibabagroup.com/en-US/ir",
    secCik: "0001577552",
    hkexCode: "9988",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["announces results", "financial results", "quarter ended", "cloud"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular"],
  },
  {
    id: "jd",
    name: "京东",
    ticker: "9618.HK",
    displayTicker: "9618.HK / JD",
    market: "HK",
    industry: "零售、电商、物流与平台服务",
    irUrl: "https://ir.jd.com/",
    secCik: "0001549802",
    hkexCode: "9618",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["announces first quarter", "financial results", "quarter ended", "logistics"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular"],
  },
  {
    id: "chineseall",
    name: "中文在线",
    ticker: "300364.SZ",
    displayTicker: "300364.SZ",
    market: "CN",
    industry: "数字阅读、IP 与 AIGC 内容",
    irUrl: "https://www.cninfo.com.cn/",
    sourceProvider: "cninfo",
    parserProfile: "pdf-text-standard",
    filingKeywords: ["季度报告", "年度报告", "营业收入", "归属于上市公司股东的净利润"],
    knownReports: {
      "2026Q1": {
        fiscalYear: 2026,
        fiscalQuarter: "Q1",
        periodLabel: "2026 Q1",
        releaseDate: "2026-04-23T00:00:00.000+08:00",
        title: "中文在线 2026年一季度报告",
        sourceUrl: "http://static.cninfo.com.cn/finalpage/2026-04-23/1225157283.PDF",
      },
    },
  },
  {
    id: "kuaishou",
    name: "快手",
    ticker: "1024.HK",
    displayTicker: "1024.HK",
    market: "HK",
    industry: "短视频、直播、广告与电商",
    irUrl: "https://ir.kuaishou.com/",
    hkexCode: "1024",
    sourceProvider: "hkex-ir",
    parserProfile: "pdf-text-standard",
    filingKeywords: ["results announcement", "quarterly results", "revenue"],
    knownReports: {
      "2026Q1": {
        fiscalYear: 2026,
        fiscalQuarter: "Q1",
        periodLabel: "2026 Q1",
        releaseDate: "2026-05-27T00:00:00.000+08:00",
        title: "Kuaishou Technology 2026 First Quarter Results Announcement",
        sourceUrl: "https://ir.kuaishou.com/static-files/51eda7e7-a9e8-43c1-b688-43f131104d98",
      },
    },
  },
  {
    id: "alphabet",
    name: "Alphabet",
    ticker: "GOOGL",
    displayTicker: "GOOGL / GOOG",
    market: "US",
    industry: "搜索、广告、云与 AI 基础设施",
    irUrl: "https://abc.xyz/investor/",
    secCik: "0001652044",
    sourceProvider: "sec",
    parserProfile: "sec-companyfacts-us-tech",
    filingForms: ["10-Q"],
    filingKeywords: ["10-Q", "quarterly report"],
  },
  {
    id: "bilibili",
    name: "哔哩哔哩",
    ticker: "9626.HK",
    displayTicker: "9626.HK / BILI",
    market: "HK",
    industry: "在线视频、社区、游戏与广告",
    irUrl: "https://ir.bilibili.com/",
    secCik: "0001723690",
    hkexCode: "9626",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["financial results", "announces first quarter", "quarter ended", "advertising"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular", "date of board meeting", "date of publication"],
  },
  {
    id: "meituan",
    name: "美团",
    ticker: "3690.HK",
    displayTicker: "3690.HK",
    market: "HK",
    industry: "本地生活、外卖、到店酒旅与新业务",
    irUrl: "https://about.meituan.com/en/investor-relations",
    hkexCode: "3690",
    sourceProvider: "hkex-ir",
    parserProfile: "pdf-text-standard",
    filingKeywords: ["results announcement", "quarterly results", "revenue"],
  },
  {
    id: "meitu",
    name: "美图",
    ticker: "1357.HK",
    displayTicker: "1357.HK",
    market: "HK",
    industry: "影像与设计 SaaS、AI 图像产品",
    irUrl: "https://corp.meitu.com/en/investor/",
    hkexCode: "1357",
    sourceProvider: "hkex-ir",
    parserProfile: "pdf-text-standard",
    filingKeywords: ["results announcement", "interim results", "annual results"],
  },
  {
    id: "zhihu",
    name: "知乎",
    ticker: "2390.HK",
    displayTicker: "2390.HK / ZH",
    market: "HK",
    industry: "社区、内容、会员与营销服务",
    irUrl: "https://ir.zhihu.com/",
    secCik: "0001835724",
    hkexCode: "2390",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["reports unaudited first quarter", "total revenues were", "paid membership"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular", "proxy", "change of non-executive director"],
  },
  {
    id: "trip",
    name: "携程",
    ticker: "9961.HK",
    displayTicker: "9961.HK / TCOM",
    market: "HK",
    industry: "在线旅游、住宿、交通票务与商旅",
    irUrl: "https://investors.trip.com/",
    secCik: "0001269238",
    hkexCode: "9961",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["financial results", "announces first quarter", "quarter ended", "accommodation"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular"],
  },
  {
    id: "tencent",
    name: "腾讯控股",
    ticker: "0700.HK",
    displayTicker: "0700.HK",
    market: "HK",
    industry: "社交、游戏、广告、金融科技与云",
    irUrl: "https://www.tencent.com/en-us/investors.html",
    hkexCode: "0700",
    sourceProvider: "hkex-ir",
    parserProfile: "pdf-text-standard",
    filingKeywords: ["results announcement", "quarterly results"],
    knownReports: {
      "2026Q1": {
        fiscalYear: 2026,
        fiscalQuarter: "Q1",
        periodLabel: "2026 Q1",
        releaseDate: "2026-05-13T00:00:00.000+08:00",
        title: "Tencent 2026 First Quarter Results Announcement",
        sourceUrl: "https://static.www.tencent.com/uploads/2026/05/13/47382ae415a209fd161bc19a1f9b3704.pdf",
      },
    },
  },
  {
    id: "weibo",
    name: "微博",
    ticker: "9898.HK",
    displayTicker: "9898.HK / WB",
    market: "HK",
    industry: "社交媒体、广告与增值服务",
    irUrl: "https://ir.weibo.com/",
    secCik: "0001595761",
    hkexCode: "9898",
    sourceProvider: "sec",
    parserProfile: "sec-6k-standard",
    filingKeywords: ["financial results", "announces first quarter", "quarter ended", "advertising"],
    excludeFilingKeywords: ["annual general meeting", "share repurchase", "circular"],
  },
  {
    id: "meta",
    name: "Meta",
    ticker: "META",
    displayTicker: "META",
    market: "US",
    industry: "社交广告、Reality Labs 与 AI 基础设施",
    irUrl: "https://investor.fb.com/",
    secCik: "0001326801",
    sourceProvider: "sec",
    parserProfile: "sec-companyfacts-us-tech",
    filingForms: ["10-Q"],
    filingKeywords: ["10-Q", "quarterly report"],
  },
  {
    id: "apple",
    name: "Apple",
    ticker: "AAPL",
    displayTicker: "AAPL",
    market: "US",
    industry: "消费电子、服务与端侧 AI",
    irUrl: "https://investor.apple.com/",
    secCik: "0000320193",
    sourceProvider: "sec",
    parserProfile: "sec-companyfacts-us-tech",
    filingForms: ["10-Q"],
    filingKeywords: ["10-Q", "quarterly report"],
  },
  {
    id: "microsoft",
    name: "微软",
    ticker: "MSFT",
    displayTicker: "MSFT",
    market: "US",
    industry: "云、软件、生产力工具与 AI",
    irUrl: "https://www.microsoft.com/en-us/investor",
    secCik: "0000789019",
    sourceProvider: "sec",
    parserProfile: "sec-companyfacts-us-tech",
    filingForms: ["10-Q"],
    filingKeywords: ["10-Q", "quarterly report"],
  },
  {
    id: "netease",
    name: "网易",
    ticker: "9999.HK",
    displayTicker: "9999.HK / NTES",
    market: "HK",
    industry: "游戏与互联网服务",
    irUrl: "https://ir.netease.com/",
    secCik: "0001110646",
    hkexCode: "9999",
    sourceProvider: "sec",
    parserProfile: "netease-q1-2026",
    filingKeywords: ["financial results", "unaudited financial results", "first quarter"],
    knownReports: {
      "2026Q1": {
        fiscalYear: 2026,
        fiscalQuarter: "Q1",
        periodLabel: "2026 Q1",
        releaseDate: "2026-05-21T18:30:00.000+08:00",
        title: "NetEase Announces First Quarter 2026 Unaudited Financial Results",
        sourceUrl:
          "https://www.sec.gov/Archives/edgar/data/1110646/000110465926064764/tm2615053d1_ex99-1.htm",
      },
    },
  },
  {
    id: "baidu",
    name: "百度",
    ticker: "9888.HK",
    displayTicker: "9888.HK / BIDU",
    market: "HK",
    industry: "搜索、广告、云与自动驾驶",
    irUrl: "https://ir.baidu.com/",
    secCik: "0001329099",
    hkexCode: "9888",
    sourceProvider: "sec",
    parserProfile: "baidu-q1-2026",
    filingKeywords: ["financial results", "quarter", "unaudited"],
    knownReports: {
      "2026Q1": {
        fiscalYear: 2026,
        fiscalQuarter: "Q1",
        periodLabel: "2026 Q1",
        releaseDate: "2026-05-18T20:00:00.000+08:00",
        title: "Baidu Announces First Quarter 2026 Results",
        sourceUrl:
          "https://www.sec.gov/Archives/edgar/data/1329099/000119312526228123/d156481dex991.htm",
      },
    },
  },
];

export function getCompanyConfig(companyId: string) {
  return trackedCompanyConfigs.find(
    (company) =>
      company.id === companyId ||
      company.ticker.toLowerCase() === companyId.toLowerCase() ||
      company.displayTicker.toLowerCase().includes(companyId.toLowerCase()),
  );
}
